# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bjorkista
email: bjorkista@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Uma brasileira, um português, um golden retriever e duas bicicletas pelo mundo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bjorkista.com" # the base hostname & protocol for your site
twitter_username: bjorkista
github_username:  bjorkista

# Build settings
markdown: kramdown
